SelectClassApplication/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SelectClassApplication.Models;
using StudentSelectClassLibrary;
using StudentSelectClassLibrary.DA;
using StudentSelectClassLibrary.Models;
using StudentSelectClassLibrary.Query;

namespace SelectClassApplication.Controllers
{
    public class AdminController : Controller
    {
        public XuanKeDBContext DBContext { get; set; }
        public IHostingEnvironment HostingEnvironment { get; set; }

        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="hostingEnvironment">路径</param>
        public AdminController(IHostingEnvironment hostingEnvironment, XuanKeDBContext db)
        {
            HostingEnvironment = hostingEnvironment;
            DBContext = db;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "学生选课系统-后台管理-首页";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult StudentResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-学生管理";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            StudentDa da = new StudentDa
            {
                XuanKeDB = DBContext
            };
            var query = new TblStudentQuery
            {
                PageIndex = 1,
                Page = 20
            };
            List<TblStudent> students = da.GetStudentsList(query);
            ViewBag.students = students;
            return View();
        }

        public IActionResult CourseResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-课程管理";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult DeptResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-院系管理";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult MajorResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-专业管理";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult ManagerResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-管理员";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult SettingResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-设置";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult TeacherResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-教师管理";
            return View();
        }

        public IActionResult SelectClassInfoResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-选课信息管理";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult StudentDetailResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-学生详情";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult CourseDetailResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-课程详情";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult DeptDetailResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-院系详情";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult MajorDetailResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-班级详情";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult ManagerDetailResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-管理员详情";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult SettingDetailResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-设置详情";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult TeacherDetailResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-教师详情";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult SelectClassInfoDetailResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-选课信息详情";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult AddStudentResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-新增学生信息";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult AddCourseResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-新增课程信息";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult AddDeptResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-新增院系信息";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult AddMajorResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-新增班级信息";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult AddManagerResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-新增管理员信息";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult AddSettingResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-新增设置信息";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        public IActionResult AddTeacherResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-新增教师信息";
            var admincode = HttpContext.Session.GetString(SessionCode.adminname);
            if (string.IsNullOrEmpty(admincode))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {

SelectClassApplication/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StudentSelectClassLibrary;
using StudentSelectClassLibrary.DA;
using StudentSelectClassLibrary.Dtos;
using StudentSelectClassLibrary.Models;

namespace SelectClassApplication.Controllers
{
    public class LoginController : Controller
    {
        public XuanKeDBContext XuanKeDB { get; set; }

        public LoginController(XuanKeDBContext xuanKeDB)
        {
            XuanKeDB = xuanKeDB;
        }

        public IActionResult LoginResult()
        {
            ViewBag.Title = "学生选课系统-学生端-登录";
            return View();
        }

        public IActionResult LoginAdminResult()
        {
            ViewBag.Title = "学生选课系统-后台管理-登录";
            return View();
        }

        /// <summary>
        /// 前端退出登录
        /// </summary>
        /// <returns></returns>
        public IActionResult LoginOutResult()
        {
            HttpContext.Session.SetString(SessionCode.username, "");
            return Redirect("../Login/LoginResult");
        }

        /// <summary>
        /// 后端退出登录
        /// </summary>
        /// <returns></returns>
        public IActionResult LoginOutAdminResult()
        {
            HttpContext.Session.SetString(SessionCode.adminname, "");
            return Redirect("../Login/LoginAdminResult");
        }

        /// <summary>
        /// 前端登录接口
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult LoginSubmit()
        {
            string xuehao = Request.Form["username"].ToString();
            string password = Request.Form["password"].ToString();
            if (string.IsNullOrEmpty(xuehao) || string.IsNullOrEmpty(password) || string.IsNullOrWhiteSpace(xuehao) || string.IsNullOrWhiteSpace(password))
            {
                return Redirect("../Login/LoginResult");
            }
            TblStudentDto dto = new TblStudentDto
            {
                StudentNum = xuehao,
                StudentPassword = password
            };
            StudentDa da = new StudentDa {
                XuanKeDB = XuanKeDB
            };
            var flag = da.StudentLogin(dto);
            if (flag)
            {
                HttpContext.Session.SetString(SessionCode.username, xuehao);
                return Redirect("../Home/StudentResult");
            }
            return Redirect("../Login/LoginResult");
        }

        /// <summary>
        /// 后端登录接口
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult LoginAdminSubmit()
        {
            string xuehao = Request.Form["username"].ToString();
            string password = Request.Form["password"].ToString();
            if (string.IsNullOrEmpty(xuehao) || string.IsNullOrEmpty(password) || string.IsNullOrWhiteSpace(xuehao) || string.IsNullOrWhiteSpace(password))
            {
                return Redirect("../Login/LoginAdminResult");
            }
            HttpContext.Session.SetString(SessionCode.adminname, xuehao);
            return Redirect("../Admin/Index");
        }
    }
}

SelectClassApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/layout.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Admin" asp-action="Index" class="navbar-brand">学生选课系统</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Admin" asp-action="Index">首页</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="DeptResult">院系管理</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="MajorResult">专业管理</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="CourseResult">课程管理</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="SelectClassInfoResult">学生选课管理</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="TeacherResult">教师管理</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="StudentResult">学生管理</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="ManagerResult">管理员</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="SettingResult">设置</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="LoginOutAdminResult">退出登录</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    <div class="container">
        <footer>
            <p>&copy; <span class="datetime"></span>  - 学生选课系统</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        function getNow(s) {
            return s < 10 ? '0' + s : s;
        }
        function getDateTime() {
            var myDate = new Date();
            //获取当前年
            var year = myDate.getFullYear();
            //获取当前月
            var month = myDate.getMonth() + 1;
            //获取当前日
            var date = myDate.getDate();
            var h = myDate.getHours();       //获取当前小时数(0-23)
            var m = myDate.getMinutes();     //获取当前分钟数(0-59)
            var s = myDate.getSeconds();
            var now = year + '月' + getNow(month) + "日" + getNow(date) + " " + getNow(h) + ':' + getNow(m) + ":" + getNow(s);
            $('.datetime').text(now);
        }
        setInterval(getDateTime, 1000);
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SelectClassApplication/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <style type="text/css">
        .header {
            width: 100%;
            margin-top: 20px;
        }

        ul { /*设置导航栏的框框*/
            margin: 30px auto; /*框框整体的位置，30px是指离网页的顶部和下部的距离，auto控制的是左右距离为自动调节*/
            width: 400px; /*框框的宽度*/
            height: 50px; /*框框的长度*/
            padding: 0px; /*将框框的padding设置为零，不然会导致框框里的内容与框边缘有间隔*/
        }

        li {
            list-style-type: none; /* 去掉li前的点 */
            float: left; /*将li设置成做浮动，变为联动*/
        }

        a {
            display: block; /*将a变成块状*/
            width: 100px; /*设置块的宽度*/
            height: 50px; /*设置块的长度*/
            font-family: Microsoft Yahei;
            line-height: 50px; /*设置字体在块中的高度*/
            background-color: #ddd;
            margin: 0px 0px; /*块里的高宽通过margin设置*/
            color: #000000;
            text-align: center; /*字体居中*/
            text-decoration: none; /*去掉下划线*/
            font-size: 16px;
        }

            a:hover {
                background-color: red;
            }

        .content {
            width: 100%;
            margin: 0 auto;
            margin-bottom: 20px;
        }

        .footer {
            margin: 0 auto;
            background-color: black;
            color: white;
            font-size: 16px;
            width: 100%;
            height: 50px;
            text-align: center;
            padding: 15px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <ul class=daohang>
            <li><a asp-area="" asp-controller="Home" asp-action="CourseResult">课程信息</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="SelectClassResult">选课信息</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="StudentResult">个人信息</a></li>
            <li><a asp-area="" asp-controller="Login" asp-action="LoginOutResult">退出登录</a></li>
        </ul>
    </div>
    <div class="container content">
        @RenderBody()
    </div>
    <div class="footer container">
        我的第一个.NET Core 网站-学生选课系统
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>